# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.8
            toxenv: py38
          - python-version: 3.9
            toxenv: py39
          - python-version: '3.10'
            toxenv: py310
          - python-version: 3.11
            toxenv: py311
          - python-version: 3.12
            toxenv: py312
          - python-version: 3.13
            toxenv: py313

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests with tox
        run: tox -e ${{ matrix.toxenv }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          name: codecov-coverage

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run lint with tox
        run: tox -e lint
