name: Publish on Tag

on:
  push:
    tags:
      - 'v*'   

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install build & upload tools
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools<61" wheel build twine

      - name: Build distributions
        run: |
          rm -rf build/ dist/ *.egg-info
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
